import { SelectOption } from '../../../Components/SelectUI/types';
import { BlockFormats, FontSizes } from './types';

export const FORMATS_OPTIONS: SelectOption[] = [
	{ id: BlockFormats.H1, name: 'Heading 1' },
	{ id: BlockFormats.H2, name: 'Heading 2' },
	{ id: BlockFormats.H3, name: 'Heading 3' },
	{ id: BlockFormats.H4, name: 'Heading 4' },
	{ id: BlockFormats.H5, name: 'Heading 5' },
	{ id: BlockFormats.H6, name: 'Heading 6' },
	{ id: BlockFormats.P, name: 'Paragraph' },
];

export const SIZES_OPTIONS: SelectOption[] = [
	{ id: FontSizes.ExtraSmall, name: 'Extra Small' },
	{ id: FontSizes.Small, name: 'Small' },
	{ id: FontSizes.Regular, name: 'Regular' },
	{ id: FontSizes.Medium, name: 'Medium' },
	{ id: FontSizes.Large, name: 'Large' },
	{ id: FontSizes.ExtraLarge, name: 'Extra Large' },
	{ id: FontSizes.Big, name: 'Big' },
	{ id: FontSizes.Big, name: 'Big' },
];

const fonts = [
	'Agency FB Negreta',
	'Agency FB',
	'Algerian',
	'Arial Black Normal',
	'Arial Negreta cursiva',
	'Arial Negreta',
	'Arial Cursiva',
	'Arial',
	'Arial Narrow',
	'Arial Narrow Negreta',
	'Arial Narrow Negreta cursiva',
	'Arial Narrow Cursiva',
	'Arial Rounded MT Bold',
	'Bahnschrift',
	'Bahnschrift Bold',
	'Bahnschrift Bold Condensed',
	'Bahnschrift Bold SemiCondensed',
	'Bahnschrift Condensed',
	'Bahnschrift Light',
	'Bahnschrift Light Condensed',
	'Bahnschrift Light SemiCondensed',
	'Bahnschrift SemiBold',
	'Bahnschrift SemiBold Condensed',
	'Bahnschrift SemiBold SemiCondensed',
	'Bahnschrift SemiCondensed',
	'Bahnschrift SemiLight',
	'Bahnschrift SemiLight Condensed',
	'Bahnschrift SemiLight SemiCondensed',
	'Baskerville Old Face',
	'Bauhaus 93',
	'Bell MT',
	'Bell MT Negreta',
	'Bell MT Cursiva',
	'Berlin Sans FB Negreta',
	'Berlin Sans FB',
	'Berlin Sans FB Demi Negreta',
	'Bernard MT Condensed',
	'Blackadder ITC',
	'Bodoni MT',
	'Bodoni MT Negreta',
	'Bodoni MT Negreta cursiva',
	'Bodoni MT Cursiva',
	'Bodoni MT Black',
	'Bodoni MT Black Cursiva',
	'Bodoni MT Condensed',
	'Bodoni MT Condensed Negreta',
	'Bodoni MT Condensed Negreta cursiva',
	'Bodoni MT Condensed Cursiva',
	'Bodoni MT Poster Compressed',
	'Book Antiqua',
	'Book Antiqua Negreta',
	'Book Antiqua Negreta cursiva',
	'Book Antiqua Cursiva',
	'Bookman Old Style',
	'Bookman Old Style Negreta',
	'Bookman Old Style Negreta cursiva',
	'Bookman Old Style Cursiva',
	'Bookshelf Symbol 7',
	'Bradley Hand ITC',
	'Britannic Bold',
	'Broadway',
	'Brush Script MT Cursiva',
	'Calibri',
	'Calibri Bold',
	'Calibri Bold Italic',
	'Calibri Italic',
	'Calibri Light',
	'Calibri Light Italic',
	'Californian FB Negreta',
	'Californian FB Cursiva',
	'Californian FB',
	'Calisto MT Negreta',
	'Calisto MT',
	'Calisto MT Negreta cursiva',
	'Calisto MT Cursiva',
	'Cambria',
	'Cambria Bold',
	'Cambria Bold Italic',
	'Cambria Italic',
	'Cambria Math',
	'Candara',
	'Candara Bold',
	'Candara Bold Italic',
	'Candara Italic',
	'Candara Light',
	'Candara Light Italic',
	'Castellar',
	'Centaur',
	'Century',
	'Century Gothic',
	'Century Gothic Negreta',
	'Century Gothic Negreta cursiva',
	'Century Gothic Cursiva',
	'Century Schoolbook',
	'Century Schoolbook Negreta',
	'Century Schoolbook Negreta cursiva',
	'Century Schoolbook Cursiva',
	'Chiller',
	'Colonna MT',
	'Comic Sans MS',
	'Comic Sans MS Negreta',
	'Comic Sans MS Negreta cursiva',
	'Comic Sans MS Cursiva',
	'Consolas',
	'Consolas Bold',
	'Consolas Bold Italic',
	'Consolas Italic',
	'Constantia',
	'Constantia Bold',
	'Constantia Bold Italic',
	'Constantia Italic',
	'Cooper Black',
	'Copperplate Gothic Bold',
	'Copperplate Gothic Light',
	'Corbel',
	'Corbel Bold',
	'Corbel Bold Italic',
	'Corbel Italic',
	'Corbel Light',
	'Corbel Light Italic',
	'Courier New Negreta cursiva',
	'Courier New Negreta',
	'Courier New Cursiva',
	'Courier New',
	'Curlz MT',
	'Ebrima',
	'Ebrima Negreta',
	'Edwardian Script ITC',
	'Elephant Cursiva',
	'Elephant',
	'Engravers MT',
	'Eras Bold ITC',
	'Eras Demi ITC',
	'Eras Light ITC',
	'Eras Medium ITC',
	'Felix Titling',
	'Footlight MT Light',
	'Forte',
	'Franklin Gothic Book',
	'Franklin Gothic Book Cursiva',
	'Franklin Gothic Demi',
	'Franklin Gothic Demi Cond',
	'Franklin Gothic Demi Cursiva',
	'Franklin Gothic Heavy',
	'Franklin Gothic Heavy Cursiva',
	'Franklin Gothic Medium',
	'Franklin Gothic Medium Cond',
	'Franklin Gothic Medium Cursiva',
	'Freestyle Script',
	'French Script MT',
	'Gabriola',
	'Gadugi',
	'Gadugi Bold',
	'Garamond',
	'Garamond Negreta',
	'Garamond Cursiva',
	'Georgia',
	'Georgia Negreta',
	'Georgia Negreta cursiva',
	'Georgia Cursiva',
	'Gigi',
	'Gill Sans Ultra Bold',
	'Gill Sans Ultra Bold Condensed',
	'Gill Sans MT',
	'Gill Sans MT Negreta',
	'Gill Sans MT Negreta cursiva',
	'Gill Sans MT Condensed',
	'Gill Sans MT Ext Condensed Bold',
	'Gill Sans MT Cursiva',
	'Gloucester MT Extra Condensed',
	'Goudy Old Style Negreta',
	'Goudy Old Style Cursiva',
	'Goudy Old Style',
	'Goudy Stout',
	'Haettenschweiler',
	'Harlow Solid Italic',
	'Harrington',
	'High Tower Text Cursiva',
	'High Tower Text',
	'HoloLens MDL2 Assets',
	'Impact',
	'Imprint MT Shadow',
	'Informal Roman',
	'Ink Free',
	'Javanese Text',
	'Jokerman',
	'Juice ITC',
	'Kristen ITC',
	'Kunstler Script',
	'Wide Latin',
	'Leelawadee',
	'Leelawadee Negreta',
	'Leelawadee UI',
	'Leelawadee UI Negreta',
	'Leelawadee UI Semilight Normal',
	'Lucida Bright',
	'Lucida Bright Demibold',
	'Lucida Bright Demibold Italic',
	'Lucida Bright Italic',
	'Lucida Calligraphy Italic',
	'Lucida Console',
	'Lucida Fax',
	'Lucida Fax halvfed',
	'Lucida Fax halvfed kursiv',
	'Lucida Fax kursiv',
	'Lucida Handwriting kursiv',
	'Lucida Sans',
	'Lucida Sans halvfed',
	'Lucida Sans halvfed kursiv',
	'Lucida Sans kursiv',
	'Lucida Sans Typewriter',
	'Lucida Sans Typewriter fed',
	'Lucida Sans Typewriter fed oblik',
	'Lucida Sans Typewriter oblik',
	'Lucida Sans Unicode',
	'MS Gothic',
	'MS PGothic',
	'MS UI Gothic',
	'MS Outlook',
	'MS Reference Sans Serif',
	'MS Reference Specialty',
	'MV Boli',
	'Magneto Negreta',
	'Maiandra GD',
	'Malgun Gothic',
	'Malgun Gothic Semilight',
	'Malgun Gothic Bold',
	'Marlett',
	'Matura MT Script Capitals',
	'Microsoft Himalaya',
	'Microsoft Yi Baiti',
	'Microsoft JhengHei Negreta',
	'Microsoft JhengHei Light',
	'Microsoft JhengHei',
	'Microsoft JhengHei UI Negreta',
	'Microsoft JhengHei UI Light',
	'Microsoft JhengHei UI',
	'Microsoft New Tai Lue',
	'Microsoft New Tai Lue Bold',
	'Microsoft PhagsPa',
	'Microsoft PhagsPa Bold',
	'Microsoft Sans Serif',
	'Microsoft Tai Le',
	'Microsoft Tai Le Bold',
	'Microsoft Uighur',
	'Microsoft Uighur Negreta',
	'Microsoft YaHei',
	'Microsoft YaHei Negreta',
	'Microsoft YaHei Light',
	'Microsoft YaHei UI',
	'Microsoft YaHei UI Negreta',
	'Microsoft YaHei UI Light',
	'MingLiU_HKSCS-ExtB',
	'MingLiU-ExtB',
	'Mistral',
	'Modern No. 20',
	'Mongolian Baiti',
	'Monotype Corsiva',
	'Myanmar Text',
	'Myanmar Text Bold',
	'NSimSun',
	'Niagara Engraved',
	'Niagara Solid',
	'Nirmala UI',
	'Nirmala UI Negreta',
	'Nirmala UI Semilight',
	'OCR A Extended',
	'Old English Text MT',
	'Onyx',
	'PMingLiU-ExtB',
	'Palace Script MT',
	'Palatino Linotype Negreta',
	'Palatino Linotype Negreta cursiva',
	'Palatino Linotype Cursiva',
	'Palatino Linotype',
	'Papyrus',
	'Parchment',
	'Perpetua',
	'Perpetua Negreta',
	'Perpetua Negreta cursiva',
	'Perpetua Cursiva',
	'Perpetua Titling MT Negreta',
	'Perpetua Titling MT Light',
	'Playbill',
	'Poor Richard',
	'Pristina',
	'Rage Italic',
	'Ravie',
	'Rockwell',
	'Rockwell Negreta',
	'Rockwell Negreta cursiva',
	'Rockwell Condensed',
	'Rockwell Condensed Negreta',
	'Rockwell Extra Bold',
	'Rockwell Cursiva',
	'Script MT Bold',
	'Segoe MDL2 Assets',
	'Segoe Print',
	'Segoe Print Bold',
	'Segoe Script',
	'Segoe Script Bold',
	'Segoe UI',
	'Segoe UI Negreta',
	'Segoe UI Negreta Cursiva',
	'Segoe UI Cursiva',
	'Segoe UI Light',
	'Segoe UI Light Italic',
	'Segoe UI Semibold',
	'Segoe UI Semibold Italic',
	'Segoe UI Semilight',
	'Segoe UI Semilight Italic',
	'Segoe UI Black',
	'Segoe UI Black Italic',
	'Segoe UI Emoji',
	'Segoe UI Historic',
	'Segoe UI Symbol',
	'Showcard Gothic',
	'SimSun',
	'SimSun-ExtB',
	'Sitka Banner',
	'Sitka Banner Bold',
	'Sitka Banner Bold Italic',
	'Sitka Banner Italic',
	'Sitka Display',
	'Sitka Display Bold',
	'Sitka Display Bold Italic',
	'Sitka Display Italic',
	'Sitka Heading',
	'Sitka Heading Bold',
	'Sitka Heading Bold Italic',
	'Sitka Heading Italic',
	'Sitka Small',
	'Sitka Small Bold',
	'Sitka Small Bold Italic',
	'Sitka Small Italic',
	'Sitka Subheading',
	'Sitka Subheading Bold',
	'Sitka Subheading Bold Italic',
	'Sitka Subheading Italic',
	'Sitka Text',
	'Sitka Text Bold',
	'Sitka Text Bold Italic',
	'Sitka Text Italic',
	'Snap ITC',
	'Stencil',
	'Sylfaen',
	'Symbol',
	'Tahoma',
	'Tahoma Negreta',
	'Tempus Sans ITC',
	'Times New Roman Negreta cursiva',
	'Times New Roman Negreta',
	'Times New Roman cursiva',
	'Times New Roman',
	'Trebuchet MS Negreta cursiva',
	'Trebuchet MS',
	'Trebuchet MS Negreta',
	'Trebuchet MS Cursiva',
	'Tw Cen MT Negreta',
	'Tw Cen MT Negreta cursiva',
	'Tw Cen MT Condensed',
	'Tw Cen MT Condensed Negreta',
	'Tw Cen MT Condensed Extra Bold',
	'Tw Cen MT Cursiva',
	'Tw Cen MT',
	'Verdana',
	'Verdana Negreta',
	'Verdana Negreta cursiva',
	'Verdana Cursiva',
	'Viner Hand ITC',
	'Vivaldi Cursiva',
	'Vladimir Script',
	'Webdings',
	'Wingdings',
	'Wingdings 2',
	'Wingdings 3',
	'Yu Gothic Bold',
	'Yu Gothic Light',
	'Yu Gothic Medium',
	'Yu Gothic Regular',
	'Yu Gothic UI Bold',
	'Yu Gothic UI Light',
	'Yu Gothic UI Regular',
	'Yu Gothic UI Semibold',
	'Yu Gothic UI Semilight',
];
